markdown: redcarpet
highlighter: rouge

permalink: pretty

url: http://nazitunnels.org
baseurl: /dissertation

author:
  name:           'Ammon Shepherd'
  url:            https://mossiso.com

include: [error_pages, .htaccess]

page_gen_dirs: true
page_gen:
  - data: 'docs'
    name: 'FileID'
    template: 'file'
    dir: 'repository/files'
