markdown: redcarpet
highlighter: rouge

permalink: pretty

url: http://nazitunnels.org
baseurl: /dissertation

author:
  name:           'Ammon Shepherd'
  url:            https://mossiso.com

include: [error_pages, .htaccess]
